project:
  type: website

website:
  title: "Chrysanthi Ainali"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
  page-footer:
    left: "(c) Chrysanthi Ainali, 2024-. [Disclaimer](disclaimer)"


format:
  html:
    theme:
      - cosmo
      - custom.scss
    toc: true
    toc_depth: 3
    toc_float: true
    toc_smooth_scroll: true
    toc_highlight: true
    fig-align: center

