name: Deploy Quarto Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: latest

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
          mkdir -p ~/R/x86_64-pc-linux-gnu-library/4.0
          echo 'R_LIBS_USER="~/R/x86_64-pc-linux-gnu-library/4.0"' >> ~/.Renviron
          Rscript -e 'install.packages("quarto", repos="http://cran.rstudio.com")'

      - name: Render Quarto site
        run: |
          quarto render

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
